#!/bin/sh
set -e

##
# vars
libexec=$(realpath "$(dirname "${0}")"/..)

##
# main
for link in $(deno run --allow-read "${libexec}"/scripts/get-links.ts); do
    deno run \
	 --allow-read \
	 --allow-env \
	 --allow-net \
	 "${libexec}"/scripts/post-link.ts "${link}"
done
